- src: https://github.com/stackhpc/ansible-role-firewallgen
  version: master
  name: stackhpc.firewallgen

- src: https://github.com/paulbrowne/stackhpc.ssm
  version: auth_token 
  name: stackhpc.ssm
